---
title: "Vaccination Data"
author: "Justin Ehly"
date: "3/15/2021"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(tidyverse)
library(tidyr)
library(ggplot2)
library(graphics)
library(ggpubr)
library(directlabels)
library(survminer)
library(magrittr)
library(naniar)
library(Hmisc)
library(scales)
library(data.table)
library(dplyr)

```


```{r read Vaccination data}

df <- read.csv('https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/us_state_vaccinations.csv')
#View(df)
# remove these locations because they are already reported in the per state data
# per:  https://covid.cdc.gov/covid-data-tracker/#vaccinations

Feds <- c("Bureau of Prisons", "Dept of Defense", "Indian Health Svc", "Veterans Health", "Long Term Care")
vacc <- df[which(df$location %nin% Feds), ]
vacc$date <- as.Date(vacc$date)
vacc$location <- as.factor(vacc$location)


missing <- sapply(vacc, function(x) sum(is.na(x)))
missing 


# impute missing data
# copy missing days from prior days
vacc <- vacc %>% dplyr::group_by(location) %>% 
  fill(where(is.numeric), .direction = "downup")

vacc <- as.data.frame(vacc)

missing <- sapply(vacc, function(x) sum(is.na(x)))
missing 

# just keep cols we need for graphing
vacc <- vacc[,c(1,2,3)]
names(vacc)[2] <- "state"

```

```{r read death data}
# get death rates from https://data.cdc.gov/Case-Surveillance/United-States-COVID-19-Cases-and-Deaths-by-State-o/9mfq-cb36

cd <- read.csv("C:/Users/justi.DATA-POWER/Documents/Github/7330-Term-Project/Data Set/United_States_COVID-19_Cases_and_Deaths_by_State_over_Time031521.csv")
#View(cd)
cd <- cd %>% arrange(submission_date) %>% arrange(state)
summary(cd)

# change date to date format
cd$submission_date <- as.Date(cd$submission_date, format = "%m/%d/%Y")
# check for missing numbers
missingCD <- sapply(cd, function(x) sum(is.na(x)))
missingCD 
# just interested in date, state (possibly not), total deaths
cd <- cd[,c(1,2,8)]



# NYC is reported separate from NY so we should rename NYC to NY
cd$state <- as.character(cd$state)
cd$state <- case_when(
  cd$state == "NYC" ~ "NY",
  TRUE ~ cd$state)
cd$state <- as.factor(cd$state)

# rename date col
names(cd)[1] <- "date"
names(cd)[2] <- "code"

# organize dataframe
cd <- cd %>% arrange(date) %>% arrange(code)

# reduce dataframe to just the date ranges we have tweets for starting 12/12/2020
cd <- cd %>% subset(date >= "2020-12-12")

str(cd)



```

```{r states table}

states <- read.csv("C:/Users/justi.DATA-POWER/Documents/Github/7330-Term-Project/Data Set/usa_states.csv")
#View(states)
names(states)[1] <- "state"
names(states)[3] <- "code"
states <- states[,c(1,3)]
states$state <- as.factor(states$state)
states$code <- as.factor(states$code)

```


```{r merge tables}
library(data.table)
# data frame combinging the state abbvs and names with death totals
newDF <- merge(cd, states, by = "code")
newDF <- newDF[,c(2,1,4,3)]
newDF$date <- as.factor(newDF$date)

newDF <- newDF %>% arrange(date) %>% arrange(code)

# date frame combining the state abbrvs and names with vacc totals
newDF2 <- merge(vacc,states, by="state")
newDF2 <- newDF2[,c(2,4,1,3)]
newDF2 <- newDF2 %>% arrange(date) %>% arrange(code) %>% subset(date < "2021-03-15")
newDF2$date <- as.factor(newDF2$date)

# create one dataframe with both death totals and vaccinations
df <- merge(newDF, newDF2, by = c("date","code","state"), all.x=TRUE, all.y=TRUE)
sapply(df, function(x) sum(is.na(x)))

# const  
# locf replaces NA's with the most recent non-NA prior to it
# nocb next observation carried backward
# setnafill part of the data.table package
df <- setnafill(df, cols="total_vaccinations", fill=0)
names(df)[5] <- "tot_vacc"

# subset the master dataframe to get totals by date instead of by state
df2 <- df %>% dplyr::group_by(date) %>% 
  dplyr::summarise(TotVax=sum(tot_vacc)/100, TotDeath=sum(tot_death))
names(df2)[2] <- "Total Vaccinations(00)" #renaming variable to show it is scales to the 100's
names(df2)[3] <- "Total Deaths"
df2 <- as.data.frame(df2)

```

```{r twitter sentiment}

sent <- read.csv("C:/Users/justi.DATA-POWER/Documents/Github/7330-Term-Project/Data Set/tweets_loc_sen0315.csv")
#View(sent)
#names(sent)
sent <- sent[,c(10,20:23)]
#str(sent)
sent$date <- as.factor(as.Date(sent$date))
sent <- rename(sent, "Mixed"="sentimentScore.mixed", 
               "Negative"= "sentimentScore.negative", "Neutral"="sentimentScore.neutral",
               "Positive" = "sentimentScore.positive")

# average each sentiment score by date
# scale to same as Total Vaccinations(00) by mult mean by df2[dim(df2)[1],2] and we will call that multiplier 'xm'
xm <- df2[dim(df2)[1],2]

sent <- sent %>% group_by(date) %>%
  dplyr::summarise("AvgMixed Sent"=mean(Mixed)*xm,
                   "AvgNegative Sent"=mean(Negative)*xm,
                   "AvgNeutral Sent"=mean(Neutral)*xm,
                   "AvgPositive Sent"=mean(Positive)*xm)
sent[93,] <- sent[92,]
sent$date <- as.character(sent$date)
sent[93,1] <- "2021-03-14"
sent$date <- as.factor(sent$date)

```


```{r combine sentiment with death and vacc}

# merge df2 + sentament analysis
sentAns <- merge(df2, sent, by="date")
sentAns <- sentAns[,-4]
#View(sentAns)


```

```{r tweets per day}

tw <- read.csv("C:/Users/justi.DATA-POWER/Documents/Github/7330-Term-Project/Data Set/tweets_loc_sen0315.csv")
#View(tw)
#names(tw)
tw <- tw[,c(10,3,17:23)]
tw <- tw[,c(1,5)]

# convert date column from char to Date
tw$date <- as.Date(tw$date)

#arrange by date
tw <- tw %>% arrange(date)

# need to have this in a data.table not a dataframe for further manipulation
is.data.table(tw)
tw <- as.data.table(tw)

# count tweets/ day (data.table function)
tweetsPerDay <- tw[, .(count = .N), by = .(date, sentiment)][]
tweetsPerDay

```

```{r plots Main Graphic}

# prep dataframe for new melt method from data.table package
sentAns$`Total Deaths` <- as.numeric(sentAns$`Total Deaths`)
sentAns <- sentAns[-c(92,93),] # remove 3/13, 3/14 per group discussion about spike in 3/13 sentiment on 9 tweets

# melt the dataframe for mapping multiple lines with different colors
dd <- melt(as.data.table(sentAns), id=c("date"))
names(dd)[2] <- "Legend"



# plot deaths and vaccines 
overallData <- 
  dd %>% 
  ggplot(aes(x=as.Date(date), y=value, color=Legend)) +
  geom_line() +
  #geom_point() +
  scale_color_manual(values = c("blue", "black", "red", "lightsteelblue3", "green")) +
  labs(x = "Months",
       y = "Covid-19 Rolling Vaccination and Death Totals") +
  scale_y_continuous(labels=comma, limits = (c(0,1050000)), 
                     sec.axis = sec_axis( ~./1050000, name = "Sentiment Score",
                                          labels = function(b) { paste0(signif(b, digits = 3)) })) +
  theme_classic() +
  theme(legend.position = "none") + 
  # old legend position in case we want to use it later theme(legend.position = c(0.12,0.86)) +
  scale_x_date(expand = expansion(add = c(1, 27))) + 
  directlabels::geom_dl(aes(label = Legend), method = list("last.polygons", cex=0.7)) +
  theme(axis.text.y.right = element_text(margin = unit(c(0, 2, 0, 2), "pt")))
  # margin usage: margin(t = 0, r = 0, b = 0, l = 0, unit = "pt") - think TRouBLe

 
```

```{r plot tweets per day}

# shorter df/ dt to work with
tpd <- tweetsPerDay
tpd$sentiment <- as.factor(tpd$sentiment)
tpd$sentiment <- factor(tpd$sentiment, levels = rev(unique(tpd$sentiment)))
tpd$sentiment <- factor(tpd$sentiment, levels = c('POSITIVE', 'NEUTRAL', 'NEGATIVE', 'MIXED'))
levels(tpd$sentiment)[1] <- "Positive"
levels(tpd$sentiment)[2] <- "Neutral"
levels(tpd$sentiment)[3] <- "Negative"
levels(tpd$sentiment)[4] <- "Mixed"

tpd <- tpd[-284,] # removing 3/13/21 row


dailytweets <- 
  tpd %>% ggplot(aes(x = date, y = count, fill = sentiment)) +
  geom_col() +
  labs( x = "Months",
        y = "Tweets per Day",
        fill = "Sentiment:") +
  scale_fill_manual(values = c('green', 'lightsteelblue3', 'red', 'lightslategrey')) +
  scale_x_date(expand = expansion(add = c(1, 27))) +
  scale_y_continuous(breaks = c(0,100,200)) +
  theme_classic() +
  theme(legend.position = "bottom", legend.text = element_text(size = 8),
        legend.title = element_text(size = 8, face = 'bold') , legend.direction = "horizontal",
        legend.key.size = unit(10, 'pt'))
  

```

```{r plots in one page}

# combine the plots one over the other
figure <- ggarrange(overallData, dailytweets, heights = c(2, 0.9),
          ncol = 1, nrow = 2, align = 'v')
af <- annotate_figure(figure,
                top = text_grob("Average Sentiment vs Total Covid-19 Vaccinations and Deaths in the USA", 
                                face = "bold", size = 12),
                bottom = text_grob("Sentiment Score is 0-1 and Scaled for this graphic. \n Data thru March 12, 2021, extra right side units are added to this graph for labels. ",
                                   face = 'italic', size=8, hjust = 1, x = 1, just = "right"))
# graphical output
af


```


```{r add lines of interest}

dates <- data.frame("Jan 20th - Inaug", "Feb 28th - J&J")

updatedGraph <- 
  overallData +
  geom_vline(data = dates, aes(xintercept = as.Date("2021-01-20")), color="blue") +
  geom_text(mapping = aes(x = as.Date("2021-01-20"),y=1050000, label = dates[1,1], angle=270, 
                          vjust = -0.5, hjust = -.01), size=4, color="blue") +
  geom_vline(data = dates, aes(xintercept = as.Date("2021-02-28")), color="blue") +
  geom_text(mapping = aes(x = as.Date("2021-02-28"),y=1050000, label = dates[1,2], angle=270, 
                          vjust = -0.5, hjust = -.01), size=4, color="blue") +
  geom_abline()


```

```{r plots with dates in one page}

# combine the plots one over the other
figure <- ggarrange(updatedGraph, dailytweets, heights = c(2, 0.9), ncol = 1, nrow = 2, align = 'v')
annotate_figure(figure,
                top = text_grob("Average Sentiment vs Total Covid-19 Vaccinations and Deaths in the USA", 
                                face = "bold", size = 12),
                bottom = text_grob("Sentiment Score is 0-1 and Scaled for this graphic. \n Data thru March 12, 2021, extra right side units are added to this graph for labels. ",
                                   face = 'italic', size=8, hjust = 1, x = 1, just = "right"))

```

